# general config
model_class: 'steel'
scenario: 'baseline_pd'

# logging
logging:
  level: 'INFO' # options: DEBUG, INFO, WARNING, ERROR, CRITICAL

# model customization
customization:
  model_driven: 'production' # options: production, final_demand, final_demand_with_start_value_and_growth_rate
  lifetime_model_name: 'NormalLifetime'

# visualization
visualization:
  inflow:
    do_visualize: False
  production:
    do_visualize: False
  outflow:
    do_visualize: False
  sankey:
    do_visualize: False
  dashboard:
    do_visualize: True

# data export
do_export:
  pickle: False
  csv: True
selected_export:
  csv_selected_flows:
    - 'sysenv => Steel product market'
    - 'Steel goods market => End use stock'
    - 'Waste management => sysenv'
  csv_selected_stocks:
    - 'End use stock'
  csv_slice_stocks:
    - 'time': [2020, 2030, 2040, 2050]
